# Generated by Django 4.2.27 on 2025-12-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_newsupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denguestat',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
    ]
