# Generated by Django 4.2.27 on 2025-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_alter_denguestat_deaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='denguestat',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='denguestat',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
