# Generated by Django 4.2.27 on 2025-12-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_newspost_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityreport',
            name='area_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
