# Generated by Django 4.2.27 on 2025-12-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_communityreport_area_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denguestat',
            name='active_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='denguestat',
            name='city_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='denguestat',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denguestat',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='denguestat',
            name='recovered',
            field=models.IntegerField(default=0),
        ),
    ]
