# Generated by Django 4.2.27 on 2025-12-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vaccinated',
            field=models.CharField(default='No', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recent_test_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
