# Generated by Django 4.2.27 on 2025-12-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_healthtip_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='city',
            field=models.CharField(default='All Pakistan', max_length=100),
        ),
    ]
